import React, { createContext, useContext, useState } from 'react';

const translations = {
    en: {
        // Sidebar
        dashboard: 'Dashboard',
        fileFIR: '+ File FIR',
        firDatabase: 'FIR Database',
        sendAlerts: 'Send Alerts',
        auditLogs: 'Audit Logs',
        settings: 'Settings',
        profile: 'Profile',
        logout: 'Logout',
        sachAdmin: 'SACH Admin',
        policePortal: 'Police Portal',

        // Header dropdown
        myProfile: 'My Profile',
        urduToggle: 'اردو میں تبدیل کریں',
        secureLogout: 'Secure Logout',

        // Dashboard Home
        myAssignedCases: 'My Assigned Cases',
        pending: 'Pending',
        active: 'Active',
        resolved: 'Resolved',
        myRecentCases: 'My Recent Cases',
        viewAll: 'View all →',
        fileNewFIR: '+ File New FIR',
        badge: 'Badge',

        // Table headers
        firNo: 'FIR No.',
        offenseCategory: 'Offense Category',
        jurisdiction: 'Jurisdiction',
        status: 'Status',
        actions: 'Actions',

        // FIR Database
        totalFIRs: 'Total FIRs',
        pendingNew: 'Pending / New',
        allFiledFIRs: 'All Filed e-FIRs',
        searchPlaceholder: 'FIR No., Category, Name, CNIC...',
        category: 'Category',
        showing: 'Showing',
        of: 'of',
        records: 'records',

        // Send Alerts
        broadcastTitle: 'Broadcast Alerts & Notifications',
        composeNewAlert: 'Compose New Alert',
        composeDesc: 'Broadcast messages to officers, citizens, or specific targets',
        targetAudience: 'Target Audience',
        selectTargetAudience: 'Select target audience...',
        alertSubject: 'Alert Subject / Title',
        enterAlertSubject: 'Enter alert subject...',
        messageBody: 'Message Body',
        composeMessage: 'Compose your alert message...',
        sendSecureAlert: 'Send Secure Alert',
        recentAlerts: 'Recent Alerts',
        total: 'total',
        viewBroadcastHistory: 'View Complete Broadcast History →',

        // Audit Logs
        auditLogsTitle: 'Audit Logs',
        totalEvents: 'Total Events',
        todayEvents: "Today's Events",
        criticalEvents: 'Critical Events',
        events: 'events',
        timestamp: 'Timestamp',
        action: 'Action',
        details: 'Details',
        user: 'User',
        ipAddress: 'IP Address',
        severity: 'Severity',
        searchAuditPlaceholder: 'Action, details, user, IP...',

        // Settings
        officerProfile: 'Officer Profile',
        fullName: 'Full Name',
        badgeNumber: 'Badge Number',
        rank: 'Rank',
        emailAddress: 'Email Address',
        phoneNumber: 'Phone Number',
        dateOfJoining: 'Date of Joining',
        jurisdictionAssignment: 'Jurisdiction & Assignment',
        city: 'City',
        district: 'District',
        policeStation: 'Police Station',
        jurisdictionNote: 'Jurisdiction changes must be requested through the IG Office portal.',
        notificationPreferences: 'Notification Preferences',
        newFirAlerts: 'New FIR Alerts',
        newFirAlertsDesc: 'Receive notifications when a new FIR is filed in your jurisdiction',
        firStatusUpdates: 'FIR Status Updates',
        firStatusUpdatesDesc: "Get notified when a case you're assigned to changes status",
        broadcastAlerts: 'Broadcast Alerts',
        broadcastAlertsDesc: 'Receive broadcast alerts from higher command',
        loginAlerts: 'Login Alerts',
        loginAlertsDesc: 'Get notified of new login sessions',
        emailDigest: 'Email Digest',
        emailDigestDesc: 'Receive a daily summary email of all activities',
        security: 'Security',
        changePassword: 'Change Password',
        lastChanged: 'Last changed 45 days ago',
        twoFactor: 'Two-Factor Authentication',
        twoFactorDesc: 'Enhance account security with 2FA',
        edit: 'Edit',
        update: 'Update',

        // Profile
        sachDigitalID: 'SACH Digital ID',
        verified: 'Verified',
        dateOfBirth: 'Date of Birth',
        gender: 'Gender',
        contactInformation: 'Contact Information',
        alternativeContact: 'Alternative Contact',
        residentialInformation: 'Residential Information',
        currentAddress: 'Current Address',
        province: 'Province',
        serviceInformation: 'Service Information',
        education: 'Education',
        rankDesignation: 'Rank / Designation',
        lastUpdated: 'Last Updated',
        securedBySACH: 'Secured by SACH • NADRA Verified',
        privacyPolicy: 'Privacy Policy',
        termsOfService: 'Terms of Service',
        helpCenter: 'Help Center',

        // FIR Detail
        citizenProfile: 'Citizen Profile',
        cnicVerified: 'CNIC Verified',
        cnicNumber: 'CNIC Number',
        contactNumber: 'Contact Number',
        incidentDescription: 'Incident Description',
        caseId: 'Case ID',
        dateReported: 'Date Reported',
        incidentType: 'Incident Type',
        fullDescription: 'Full Description',
        incidentLocation: 'Incident Location',
        attachedEvidence: 'Attached Evidence',
        filesAttached: 'files attached',
        immutableAuditTrail: 'Immutable Audit Trail',
        blockchainHash: 'Blockchain Hash',
        saveChanges: 'Save Changes',
        add: '+ Add',

        // Assign Officer modal
        assignOfficer: 'Assign Officer',
        assignDesc: 'Select an officer to assign to this case',
        currentlyAssigned: 'Currently Assigned',
        noOfficerAssigned: 'No officer assigned',
        searchOfficers: 'Search by name, badge, or station...',
        available: 'Available',
        unavailable: 'Unavailable',
        close: 'Close',

        // File New FIR wizard
        fileNewFIRTitle: 'File New FIR',
        citizenInfo: 'Citizen Info',
        location: 'Location',
        detailsStep: 'Details',
        evidenceReview: 'Evidence & Review',
        citizenInformation: 'Citizen Information',
        enterComplainantDetails: "Enter the complainant's personal details.",
        cnicNumberLabel: 'CNIC Number',
        selectGender: 'Select gender',
        male: 'Male',
        female: 'Female',
        other: 'Other',
        locationDetails: 'Location Details',
        provideLocationInfo: 'Provide the incident location information.',
        streetAddress: 'Street Address',
        enterCompleteAddress: 'Enter complete address',
        selectCity: 'Select City',
        selectDistrict: 'Select District',
        selectCityFirst: 'Select City First',
        mapIntegration: 'Map integration area',
        locationAutoFills: 'Location auto-fills from address',
        incidentDetails: 'Incident Details',
        describeIncident: 'Describe the incident with relevant information.',
        incidentDate: 'Incident Date',
        incidentTime: 'Incident Time',
        incidentCategory: 'Incident Category',
        selectIncidentType: 'Select incident type',
        incidentDescriptionLabel: 'Incident Description',
        describeInDetail: 'Describe the incident in detail…',
        characters: 'characters',
        voiceToText: 'Tap the microphone icon to use voice-to-text',
        uploadEvidence: 'Upload Evidence',
        addPhotosVideos: 'Add photos or videos to support the complaint.',
        evidenceAdded: 'Evidence Added ✔',
        tapToUpload: 'Tap to upload photo/video evidence',
        maxSize: '(Max 25MB)',
        evidenceOptional: 'Evidence is optional. You can attach it later from the FIR Database.',
        firSummary: 'FIR Summary',
        name: 'Name',
        cnic: 'CNIC',
        date: 'Date',
        cancel: 'Cancel',
        back: '← Back',
        nextStep: 'Next Step →',
        submitSecureFIR: 'Submit Secure e-FIR',
        eFIRSubmitted: 'e-FIR Submitted!',
        complaintFiled: 'Your complaint has been securely filed and anchored to the Hyperledger Blockchain.',
        viewDashboard: 'View Dashboard',

        // Search
        search: 'Search...',

        // Settings — Appearance & Language
        appearanceLanguage: 'Appearance & Language',
        languageToggle: 'Language',
        languageToggleDesc: 'Switch between English and Urdu interface',
        compactMode: 'Compact Mode',
        compactModeDesc: 'Reduce spacing and padding across the interface',
        showAnimations: 'Show Animations',
        showAnimationsDesc: 'Enable smooth transitions and micro-animations',
        highContrast: 'High Contrast',
        highContrastDesc: 'Increase contrast for better visibility',

        // Settings — Security extras
        sessionTimeout: 'Session Timeout',
        sessionTimeoutDesc: 'Automatically lock after period of inactivity',
        never: 'Never',

        // Settings — Data & Privacy
        dataPrivacy: 'Data & Privacy',
        activityLogging: 'Activity Logging',
        activityLoggingDesc: 'Record all actions for audit trail compliance',
        autoLock: 'Auto-Lock Screen',
        autoLockDesc: 'Lock screen when stepping away from the terminal',
        shareAnalytics: 'Share Usage Analytics',
        shareAnalyticsDesc: 'Help improve SACH by sharing anonymous usage data',
        exportData: 'Export My Data',
        clearCache: 'Clear Cache',

        // Settings — About
        about: 'About',
        version: 'Version',
        platform: 'Platform',
        buildDate: 'Build Date',
        serverRegion: 'Server Region',
        changesSaved: 'Settings saved successfully',
    },
    ur: {
        dashboard: 'ڈیش بورڈ',
        fileFIR: '+ ایف آئی آر درج کریں',
        firDatabase: 'ایف آئی آر ڈیٹابیس',
        sendAlerts: 'الرٹ بھیجیں',
        auditLogs: 'آڈٹ لاگز',
        settings: 'ترتیبات',
        profile: 'پروفائل',
        logout: 'لاگ آؤٹ',
        sachAdmin: 'ساچ ایڈمن',
        policePortal: 'پولیس پورٹل',

        myProfile: 'میرا پروفائل',
        urduToggle: 'Switch to English',
        secureLogout: 'محفوظ لاگ آؤٹ',

        myAssignedCases: 'میرے تفویض کردہ مقدمات',
        pending: 'زیر التوا',
        active: 'فعال',
        resolved: 'حل شدہ',
        myRecentCases: 'میرے حالیہ مقدمات',
        viewAll: 'سب دیکھیں ←',
        fileNewFIR: '+ نئی ایف آئی آر',
        badge: 'بیج',

        firNo: 'ایف آئی آر نمبر',
        offenseCategory: 'جرم کی قسم',
        jurisdiction: 'دائرہ اختیار',
        status: 'حالت',
        actions: 'اقدامات',

        totalFIRs: 'کل ایف آئی آر',
        pendingNew: 'زیر التوا / نئی',
        allFiledFIRs: 'تمام درج شدہ ایف آئی آر',
        searchPlaceholder: 'ایف آئی آر نمبر، قسم، نام، شناختی کارڈ...',
        category: 'قسم',
        showing: 'دکھا رہا ہے',
        of: 'میں سے',
        records: 'ریکارڈز',

        broadcastTitle: 'براڈکاسٹ الرٹ اور اطلاعات',
        composeNewAlert: 'نیا الرٹ تحریر کریں',
        composeDesc: 'افسران، شہریوں یا مخصوص اہداف کو پیغامات بھیجیں',
        targetAudience: 'ہدف سامعین',
        selectTargetAudience: 'ہدف سامعین منتخب کریں...',
        alertSubject: 'الرٹ عنوان',
        enterAlertSubject: 'الرٹ عنوان درج کریں...',
        messageBody: 'پیغام کا متن',
        composeMessage: 'اپنا الرٹ پیغام تحریر کریں...',
        sendSecureAlert: 'محفوظ الرٹ بھیجیں',
        recentAlerts: 'حالیہ الرٹ',
        total: 'کل',
        viewBroadcastHistory: 'مکمل براڈکاسٹ ریکارڈ دیکھیں ←',

        auditLogsTitle: 'آڈٹ لاگز',
        totalEvents: 'کل واقعات',
        todayEvents: 'آج کے واقعات',
        criticalEvents: 'اہم واقعات',
        events: 'واقعات',
        timestamp: 'وقت',
        action: 'اقدام',
        details: 'تفصیلات',
        user: 'صارف',
        ipAddress: 'آئی پی ایڈریس',
        severity: 'شدت',
        searchAuditPlaceholder: 'اقدام، تفصیلات، صارف، آئی پی...',

        officerProfile: 'افسر پروفائل',
        fullName: 'پورا نام',
        badgeNumber: 'بیج نمبر',
        rank: 'عہدہ',
        emailAddress: 'ای میل ایڈریس',
        phoneNumber: 'فون نمبر',
        dateOfJoining: 'تاریخ الحاق',
        jurisdictionAssignment: 'دائرہ اختیار اور تفویض',
        city: 'شہر',
        district: 'ضلع',
        policeStation: 'تھانہ',
        jurisdictionNote: 'دائرہ اختیار کی تبدیلیوں کی درخواست آئی جی آفس پورٹل کے ذریعے کی جانی چاہیے۔',
        notificationPreferences: 'اطلاعات کی ترتیبات',
        newFirAlerts: 'نئی ایف آئی آر الرٹ',
        newFirAlertsDesc: 'جب آپ کے دائرہ اختیار میں نئی ایف آئی آر درج ہو تو اطلاع حاصل کریں',
        firStatusUpdates: 'ایف آئی آر حالت اپ ڈیٹ',
        firStatusUpdatesDesc: 'جب آپ کے تفویض کردہ مقدمے کی حالت بدلے تو اطلاع حاصل کریں',
        broadcastAlerts: 'براڈکاسٹ الرٹ',
        broadcastAlertsDesc: 'اعلیٰ کمان سے براڈکاسٹ الرٹ حاصل کریں',
        loginAlerts: 'لاگ ان الرٹ',
        loginAlertsDesc: 'نئے لاگ ان سیشنز کی اطلاع حاصل کریں',
        emailDigest: 'ای میل خلاصہ',
        emailDigestDesc: 'تمام سرگرمیوں کا روزانہ خلاصہ ای میل حاصل کریں',
        security: 'سیکیورٹی',
        changePassword: 'پاس ورڈ تبدیل کریں',
        lastChanged: '45 دن پہلے تبدیل کیا گیا',
        twoFactor: 'دو عنصری تصدیق',
        twoFactorDesc: '2FA کے ذریعے اکاؤنٹ کی سیکیورٹی بہتر بنائیں',
        edit: 'تدوین',
        update: 'اپ ڈیٹ',

        sachDigitalID: 'ساچ ڈیجیٹل شناخت',
        verified: 'تصدیق شدہ',
        dateOfBirth: 'تاریخ پیدائش',
        gender: 'جنس',
        contactInformation: 'رابطہ کی معلومات',
        alternativeContact: 'متبادل رابطہ',
        residentialInformation: 'رہائشی معلومات',
        currentAddress: 'موجودہ پتہ',
        province: 'صوبہ',
        serviceInformation: 'سروس معلومات',
        education: 'تعلیم',
        rankDesignation: 'عہدہ / تقرر',
        lastUpdated: 'آخری اپ ڈیٹ',
        securedBySACH: 'ساچ ● نادرا تصدیق شدہ',
        privacyPolicy: 'رازداری پالیسی',
        termsOfService: 'شرائط خدمت',
        helpCenter: 'مدد مرکز',

        citizenProfile: 'شہری پروفائل',
        cnicVerified: 'شناختی کارڈ تصدیق شدہ',
        cnicNumber: 'شناختی کارڈ نمبر',
        contactNumber: 'رابطہ نمبر',
        incidentDescription: 'واقعے کی تفصیل',
        caseId: 'کیس آئی ڈی',
        dateReported: 'رپورٹ کی تاریخ',
        incidentType: 'واقعے کی قسم',
        fullDescription: 'مکمل تفصیل',
        incidentLocation: 'واقعے کا مقام',
        attachedEvidence: 'منسلک ثبوت',
        filesAttached: 'فائلیں منسلک',
        immutableAuditTrail: 'بلاک چین آڈٹ ٹریل',
        blockchainHash: 'بلاک چین ہیش',
        saveChanges: 'تبدیلیاں محفوظ کریں',
        add: '+ شامل کریں',

        assignOfficer: 'افسر تفویض کریں',
        assignDesc: 'اس مقدمے کے لیے افسر منتخب کریں',
        currentlyAssigned: 'فی الحال تفویض',
        noOfficerAssigned: 'کوئی افسر تفویض نہیں',
        searchOfficers: 'نام، بیج، یا تھانے سے تلاش کریں...',
        available: 'دستیاب',
        unavailable: 'غیر دستیاب',
        close: 'بند کریں',

        // File New FIR wizard
        fileNewFIRTitle: 'نئی ایف آئی آر درج کریں',
        citizenInfo: 'شہری معلومات',
        location: 'مقام',
        detailsStep: 'تفصیلات',
        evidenceReview: 'ثبوت اور جائزہ',
        citizenInformation: 'شہری معلومات',
        enterComplainantDetails: 'شکایت کنندہ کی ذاتی تفصیلات درج کریں۔',
        cnicNumberLabel: 'شناختی کارڈ نمبر',
        selectGender: 'جنس منتخب کریں',
        male: 'مرد',
        female: 'عورت',
        other: 'دیگر',
        locationDetails: 'مقام کی تفصیلات',
        provideLocationInfo: 'واقعے کے مقام کی معلومات فراہم کریں۔',
        streetAddress: 'گلی کا پتہ',
        enterCompleteAddress: 'مکمل پتہ درج کریں',
        selectCity: 'شہر منتخب کریں',
        selectDistrict: 'ضلع منتخب کریں',
        selectCityFirst: 'پہلے شہر منتخب کریں',
        mapIntegration: 'نقشے کا علاقہ',
        locationAutoFills: 'مقام خود بخود پتے سے بھرتا ہے',
        incidentDetails: 'واقعے کی تفصیلات',
        describeIncident: 'متعلقہ معلومات کے ساتھ واقعے کی تفصیل بیان کریں۔',
        incidentDate: 'واقعے کی تاریخ',
        incidentTime: 'واقعے کا وقت',
        incidentCategory: 'واقعے کی قسم',
        selectIncidentType: 'واقعے کی قسم منتخب کریں',
        incidentDescriptionLabel: 'واقعے کی تفصیل',
        describeInDetail: 'واقعے کی تفصیل بیان کریں…',
        characters: 'حروف',
        voiceToText: 'آواز سے متن کے لیے مائیکروفون آئیکن دبائیں',
        uploadEvidence: 'ثبوت اپ لوڈ کریں',
        addPhotosVideos: 'شکایت کی حمایت میں تصاویر یا ویڈیوز شامل کریں۔',
        evidenceAdded: 'ثبوت شامل کیا گیا ✔',
        tapToUpload: 'تصویر/ویڈیو ثبوت اپ لوڈ کرنے کے لیے ٹیپ کریں',
        maxSize: '(زیادہ سے زیادہ 25MB)',
        evidenceOptional: 'ثبوت اختیاری ہے۔ آپ اسے بعد میں ایف آئی آر ڈیٹابیس سے منسلک کر سکتے ہیں۔',
        firSummary: 'ایف آئی آر خلاصہ',
        name: 'نام',
        cnic: 'شناختی کارڈ',
        date: 'تاریخ',
        cancel: 'منسوخ',
        back: 'واپس ←',
        nextStep: 'اگلا مرحلہ →',
        submitSecureFIR: 'محفوظ ای-ایف آئی آر جمع کریں',
        eFIRSubmitted: 'ای-ایف آئی آر جمع ہو گئی!',
        complaintFiled: 'آپ کی شکایت محفوظ طریقے سے درج ہو کر ہائپر لیجر بلاک چین پر محفوظ ہو گئی ہے۔',
        viewDashboard: 'ڈیش بورڈ دیکھیں',

        search: 'تلاش...',

        // Settings — Appearance & Language
        appearanceLanguage: 'ظاہری شکل اور زبان',
        languageToggle: 'زبان',
        languageToggleDesc: 'انگریزی اور اردو انٹرفیس کے درمیان تبدیل کریں',
        compactMode: 'کمپیکٹ موڈ',
        compactModeDesc: 'انٹرفیس میں جگہ اور پیڈنگ کم کریں',
        showAnimations: 'اینیمیشنز دکھائیں',
        showAnimationsDesc: 'ہموار ٹرانزیشنز اور مائیکرو اینیمیشنز فعال کریں',
        highContrast: 'ہائی کنٹراسٹ',
        highContrastDesc: 'بہتر مرئیت کے لیے کنٹراسٹ بڑھائیں',

        // Settings — Security extras
        sessionTimeout: 'سیشن ٹائم آؤٹ',
        sessionTimeoutDesc: 'غیر فعالیت کے دورانیے کے بعد خود بخود لاک ہو جائے',
        never: 'کبھی نہیں',

        // Settings — Data & Privacy
        dataPrivacy: 'ڈیٹا اور رازداری',
        activityLogging: 'سرگرمی لاگنگ',
        activityLoggingDesc: 'آڈٹ ٹریل کی تعمیل کے لیے تمام اعمال ریکارڈ کریں',
        autoLock: 'آٹو لاک اسکرین',
        autoLockDesc: 'ٹرمینل سے دور ہونے پر اسکرین لاک کریں',
        shareAnalytics: 'استعمال کے تجزیات شیئر کریں',
        shareAnalyticsDesc: 'گمنام استعمال ڈیٹا شیئر کر کے ساچ کو بہتر بنانے میں مدد کریں',
        exportData: 'میرا ڈیٹا ایکسپورٹ کریں',
        clearCache: 'کیش صاف کریں',

        // Settings — About
        about: 'متعلقہ',
        version: 'ورژن',
        platform: 'پلیٹ فارم',
        buildDate: 'تعمیر کی تاریخ',
        serverRegion: 'سرور ریجن',
        changesSaved: 'ترتیبات کامیابی سے محفوظ ہو گئیں',
    },
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
    const [lang, setLang] = useState('en');
    const t = (key) => translations[lang]?.[key] || translations.en[key] || key;
    const toggleLang = () => setLang(l => l === 'en' ? 'ur' : 'en');
    const isUrdu = lang === 'ur';
    const fontFamily = isUrdu ? "'Noto Sans Arabic', 'Roboto', sans-serif" : "'Roboto', sans-serif";
    const fontSize = isUrdu ? '0.92em' : undefined;
    const dir = isUrdu ? 'rtl' : 'ltr';

    return (
        <LanguageContext.Provider value={{ lang, t, toggleLang, isUrdu, fontFamily, fontSize, dir }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);
